# JQL
BEGIN_TRANSACTION = "BEGIN TRANSACTION"
END_TRANSACTION = "END TRANSACTION"
PUT = "PUT"
DELETE = "DELETE"
GET = "GET"
TERMINATOR = ";"
KEY = "key"
VALUE = "value"
TXN = "txn"
OK = "OK"
SYNTAX_ERR = "SYNTAX ERR"

# MISC
MAX_UINT_64 = 2 ** 64 - 1
BIT_TOMBSTONE = 1 << 0
