classDiagram
  Node1 --> Node2
  Node1 --> Node3
  class Node1{
    key: (b'baz\xff\xff\xff\xff\xff\xff\xff\xfc', 54)
  }
  class Node2{
    key: (b'bar\xff\xff\xff\xff\xff\xff\xff\xfd', 27)
  }
  class Node3{
    key: (b'foo\xff\xff\xff\xff\xff\xff\xff\xfe', 0)
  }
          